#!/usr/bin/with-contenv bash

# ENVS to replcase
prsql_admin=${PRSQL_ADMIN:-admin}
prsql_password=${PRSQL_PASSWORD:-admin}
prsql_a_port=${PRSQL_A_PORT:-6032}
prsql_c_port=${PRSQL_C_PORT:-3306}
mysql_hostname=${MYSQL_HOSTNAME:-mysql}
mysql_port=${MYSQL_PORT:-3306}

mysql_user=${MYSQL_USER:-user}
mysql_password=${MYSQL_PASSWORD:-passwd}

sed \
  -e "s/PRSQL_ADMIN/${prsql_admin}/g" \
  -e "s/PRSQL_PASSWORD/${prsql_password}/g" \
  -e "s/PRSQL_A_PORT/${prsql_a_port}/g" \
  -e "s/PRSQL_C_PORT/${prsql_c_port}/g" \
  -e "s/MYSQL_HOSTNAME/${mysql_hostname}/g" \
  -e "s/MYSQL_PORT/${mysql_port}/g" \
  /etc/proxysql.cnf -i

sed \
  -e "s/MYSQL_USER/${mysql_user}/g" \
  -e "s/MYSQL_PASSWORD/${mysql_password}/g" \
  /etc/proxysql_user.cnf -i
