name: Docker Image CI

on:
  push:
    branches:
      - main
    tags:
       - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Branch name
      id: branch_name
      run: |
        echo SOURCE_NAME=${GITHUB_REF#refs/*/} >> $GITHUB_ENV
        echo SOURCE_BRANCH=${GITHUB_REF#refs/*/} >> $GITHUB_ENV
        echo SOURCE_TAG=${GITHUB_REF#refs/tags/} >> $GITHUB_ENV
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and Push the Docker image (main)
      if: ${{ github.ref == 'refs/heads/main' }}
      run: |
        docker build . --file Dockerfile --tag getshifter/proxysql:latest
        docker push getshifter/proxysql:latest
    - name: Build and Push the Docker image (TAG)
      if: ${{ github.ref != 'refs/heads/main' }}
      run: |
        docker build . --file Dockerfile --tag getshifter/proxysql:${{ env.SOURCE_TAG}}
        docker push getshifter/proxysql:${{ env.SOURCE_TAG}}
